pdf_viewer: &pdf_viewer 'pdfjs_viewer.html'

collections:
    '':
        index_paths: $liveweb
        wb_handler_class: !!python/name:via.rewriter.TemplateRewriteHandler
        templates:
            'application/pdf': *pdf_viewer
            'application/x-pdf': *pdf_viewer

        #frame_insert_html: ./templates/frame_insert.html
        #head_insert_html: ./templates/head_insert.html
        redir_to_exact: false

        #cookie_scope: host

        rewrite_opts:
            rewrite_rel_canon: false
            client:
                no_rewrite_prefixes:
                    - 'https://hypothes.is/'
                    - 'https://stage.hypothes.is/'
                    - '/assets/'

                #skip_createElement: true

                http_cache: pass

                #skip_setAttribute: true
                #skip_dom: true
                #skip_postmessage: true

search_html: index.html
home_html: index.html

framed_replay: false
